# Profiles Config for Clash Verge

current: RZP7H6NdxGYe
items:
- uid: Merge
  type: merge
  name: null
  file: Merge.yaml
  updated: 1769316801
- uid: Script
  type: script
  name: null
  file: Script.js
  updated: 1769316801
- uid: m08EuJEzUy4s
  type: merge
  name: null
  file: m08EuJEzUy4s.yaml
  updated: 1769319579
- uid: sUyVz0XZnn0k
  type: script
  name: null
  file: sUyVz0XZnn0k.js
  updated: 1769319579
- uid: rJQHYm7I7GL7
  type: rules
  name: null
  file: rJQHYm7I7GL7.yaml
  updated: 1769319579
- uid: p1lGL6M1h9Zr
  type: proxies
  name: null
  file: p1lGL6M1h9Zr.yaml
  updated: 1769319579
- uid: geye6fY1m9jK
  type: groups
  name: null
  file: geye6fY1m9jK.yaml
  updated: 1769319579
- uid: RZP7H6NdxGYe
  type: remote
  name: 00154416-5905-49a0-b75f-bbbe1fdf932a
  file: RZP7H6NdxGYe.yaml
  url: https://kaimenlai.com/clashx/00154416-5905-49a0-b75f-bbbe1fdf932a
  selected:
  - name: Proxy
    now: Auto
  extra:
    upload: 44943889
    download: 2857316612
    total: 107374182400
    expire: 1782230400
  updated: 1778248800
  option:
    allow_auto_update: true
    merge: m08EuJEzUy4s
    script: sUyVz0XZnn0k
    rules: rJQHYm7I7GL7
    proxies: p1lGL6M1h9Zr
    groups: geye6fY1m9jK
